apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname-win
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - data:
        - key: DB_HOST
          objectName: DB_HOST # name of the mounted content to sync. this could be the object name or object alias
        - key: DB_NAME
          objectName: DB_NAME
        - key: DB_PASSWORD
          objectName: DB_PASSWORD
        - key: DB_PORT
          objectName: DB_PORT
        - key: DB_USER
          objectName: DB_USER
      secretName: akvsecretscertwin
      type: Opaque

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "4fb26af4-5c1e-4995-bb77-aab44dc386db" #assign identity client_id
    keyvaultName: pollkeyvault1201456 # the name of the KeyVault
    cloudName: AzurePublicCloud # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: DBHost
          objectAlias: DB_HOST
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBName
          objectAlias: DB_NAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBPassword
          objectAlias: DB_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBPort
          objectAlias: DB_PORT
          objectType: secret
          objectVersion: ""
        - |
          objectName: DBUser
          objectAlias: DB_USER
          objectType: secret
          objectVersion: ""
    resourceGroup: "poll-app-rg" #provide azure key vault resourceGroup
    subscriptionId: "d9fd8068-6e3b-46d6-9951-5cf3dbf74daa" # subscriptionId
    tenantId: "fa0fd8d2-d414-482c-a2a3-d86969b5c5fc" # TenantId